  services:
    order-service:
      restart: always
      build:
        context: ..
        dockerfile: deploy/order-service.Dockerfile
      ports:
        - "8081:8080"

    loyalty-service:
      restart: always
      build:
        context: ..
        dockerfile: deploy/loyalty-service.Dockerfile
      ports:
        - "8082:8080"

    sso-service:
      restart: always
      build:
        context: ..
        dockerfile: deploy/sso-service.Dockerfile
      ports:
        - "5000:5000"

    postgres:
      image: postgres:14
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
      ports:
        - "5432:5432"
      volumes:
        - pgdata:/var/lib/postgresql/data

    zookeeper:
      image: confluentinc/cp-zookeeper:7.2.1
      environment:
        ZOOKEEPER_CLIENT_PORT: 2181
        ZOOKEEPER_TICK_TIME: 2000

    kafka:
      image: confluentinc/cp-kafka:7.2.1
      depends_on:
        - zookeeper
      ports:
        - "9092:9092"
      environment:
        KAFKA_BROKER_ID: 1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
        KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  volumes:
    pgdata: