name: autotests

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      postgres:
          image: postgres
          env:
            POSTGRES_PASSWORD: postgres
            POSTGRES_DB: praktikum
          options: >-
            --health-cmd pg_isready
            --health-interval 5s
            --health-timeout 5s
            --health-retries 5

      order_service:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: order_service
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      loyalty_service:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: loyalty_service
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      sso_service:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: sso_service
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "cub kafka-ready -b kafka:9092 1 20"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: "*"
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophermarttest /usr/local/bin/gophermarttest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Prepare binaries
        run: |
          mkdir -p ./bin
          (cd order-service/cmd/gophermart && go build -buildvcs=false -o $GITHUB_WORKSPACE/bin/gophermart)
          (cd order-service/cmd/accrual && chmod +x accrual_linux_amd64 && cp accrual_linux_amd64 $GITHUB_WORKSPACE/bin/)
          (cd loyalty-service/cmd && go build -buildvcs=false -o $GITHUB_WORKSPACE/bin/loyalty)
          (cd sso-service/cmd && go build -buildvcs=false -o $GITHUB_WORKSPACE/bin/sso)

      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Init DB schema
        run: |
          PGPASSWORD=postgres psql -h order_service -U postgres -d order_service -f sql/migrations/init_order.sql
          PGPASSWORD=postgres psql -h loyalty_service -U postgres -d loyalty_service -f sql/migrations/init_loyalty.sql
          PGPASSWORD=postgres psql -h sso_service -U postgres -d sso_service -f sql/migrations/init_sso.sql

      - name: Wait for PostgreSQL
        run: |
          echo "Waiting for order_service..."
          until pg_isready -h order_service -p 5432 -U postgres; do sleep 1; done
          echo "Waiting for loyalty_service..."
          until pg_isready -h loyalty_service -p 5432 -U postgres; do sleep 1; done
          echo "Waiting for sso_service..."
          until pg_isready -h sso_service -p 5432 -U postgres; do sleep 1; done
        
      - name: Install Kafka CLI
        run: |
          curl -fSL https://archive.apache.org/dist/kafka/3.7.0/kafka_2.13-3.7.0.tgz -o kafka.tgz
          tar -xzf kafka.tgz
          echo "$PWD/kafka_2.13-3.7.0/bin" >> $GITHUB_PATH

      - name: Wait for Kafka
        run: |
          echo "Waiting for Kafka..."
          for i in {1..20}; do
            if kafka-topics.sh --bootstrap-server kafka:9092 --list; then
              echo "Kafka is ready"
              break
            fi
            echo "Kafka not ready yet..."
            sleep 5
          done

      - name: Init Kafka topics
        run: |
          echo "Creating Kafka topics..."
          kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic order-created
          kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic order-completed
          kafka-topics.sh --create --if-not-exists --bootstrap-server kafka:9092 --replication-factor 1 --partitions 1 --topic order-status

      - name: Test
        env:
          DB_DSN: postgresql://postgres:postgres@order_service/order_service?sslmode=disable
          ACCRUAL_DB_DSN: postgresql://postgres:postgres@loyalty_service/loyalty_service?sslmode=disable
          SSO_DB_DSN: postgresql://postgres:postgres@sso_service/sso_service?sslmode=disable
        run: |
          echo "Using DB_DSN: $DB_DSN"
          ./bin/sso &
          sleep 5
          ./bin/loyalty &
          sleep 5
          echo "Waiting for services to be ready..."
          sleep 10
          gophermarttest \
            -test.v -test.run=^TestGophermart$ \
            -gophermart-binary-path=$GITHUB_WORKSPACE/bin/gophermart \
            -gophermart-host=localhost \
            -gophermart-port=8080 \
            -gophermart-database-uri="$DB_DSN" \
            -accrual-binary-path=$GITHUB_WORKSPACE/bin/accrual_linux_amd64 \
            -accrual-host=localhost \
            -accrual-port=$(random unused-port) \
            -accrual-database-uri="postgresql://postgres:postgres@/praktikum?sslmode=disable"
