name: gophermart

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - master

jobs:

  build:
    runs-on: ubuntu-latest
    container: golang:1.23

    services:
      order_service:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: order_service
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5
      loyalty_service:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: loyalty_service
        options: >-
          --health-cmd pg_isready
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      zookeeper:
        image: confluentinc/cp-zookeeper:7.4.0
        env:
          ZOOKEEPER_CLIENT_PORT: 2181
          ZOOKEEPER_TICK_TIME: 2000

      kafka:
        image: confluentinc/cp-kafka:7.4.0
        env:
          KAFKA_BROKER_ID: 1
          KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        options: >-
          --health-cmd "cub kafka-ready -b kafka:9092 1 20"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download autotests binaries
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: "*"
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools
          mv $GITHUB_WORKSPACE/.tools/gophermarttest /usr/local/bin/gophermarttest
          mv $GITHUB_WORKSPACE/.tools/random /usr/local/bin/random

      - name: Prepare binaries
        run: |
          (cd order-service/cmd/gophermart && go build -buildvcs=false -o /usr/local/bin/gophermart)
          (cd order-service/cmd/accrual && chmod +x accrual_linux_amd64)
          (cd loyalty-service/cmd/ && go build -buildvcs=false -o loyalty -o /usr/local/bin/loyalty)

      - name: Start services
        run: |
          gophermart &
          loyalty &
          sleep 5
        
      - name: Install PostgreSQL client
        run: apt-get update && apt-get install -y postgresql-client

      - name: Init DB schema
        run: |
          PGPASSWORD=postgres psql -h order_service -U postgres -d order_service -f sql/init_order.sql
          PGPASSWORD=postgres psql -h loyalty_service -U postgres -d loyalty_service -f sql/init_loyalty.sql

      - name: Test
        env:
          DB_DSN: postgresql://postgres:postgres@order_service/order_service?sslmode=disable
          ACCRUAL_DB_DSN: postgresql://postgres:postgres@loyalty_service/order_service?sslmode=disable

        run: |
          gophermarttest \
            -test.v -test.run=^TestGophermart$ \
            -gophermart-binary-path=order-service/cmd/gophermart/gophermart \
            -gophermart-host=localhost \
            -gophermart-port=8080 \
            -gophermart-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable" \
            -accrual-binary-path=order-service/cmd/accrual/accrual_linux_amd64 \
            -accrual-host=localhost \
            -accrual-port=$(random unused-port) \
            -accrual-database-uri="postgresql://postgres:postgres@postgres/praktikum?sslmode=disable"
